### ISSUE TITLE
Add a clearer error message during compilation if a ingredient is of the wrong provided type for an interaction.

### ISSUE THREAD

**Issue by Tim-Linschoten** [ing-bank/baker#104]
See below an example of a interaction with a difference between what the interaction expects and what the recipe provides.

Interaction 'CreateMatrix' expects ingredient 'requesterInformation:RecordType(WrappedArray(RecordField(ingId,PrimitiveType(class java.lang.String)), RecordField(firstName,PrimitiveType(class java.lang.String)), RecordField(lastName,PrimitiveType(class java.lang.String))))', however incompatible type: 'RecordType(WrappedArray())' was provided,

This is not readable for the user.

**Comment by merlijn** [comment]
#124 Is related. Both are concerned with confusing error messages on type validation.
