### ISSUE TITLE
Mark executed interactions in the visual state of a recipe

### ISSUE THREAD

**Issue by davfo224** [ing-bank/baker#111]
Hi

Currently, the visual state of the recipe shows which events were fired and which ingredients were also produced. It is really nice and provides already a very good understanding of what happened. The interactions however are still in blue and only by looking at the graph, it is possible to understand which interactions were executed.
Would it be possible to also change the color of the executed interactions to green (like the events and ingredients)?

David

**Comment by merlijn** [comment]
Yes, this is certainly possible. We will look in to this.

**Comment by merlijn** [comment]
Just committed a fix for this. Will be released in 1.4.0.
