### ISSUE TITLE
Timeout passed to 'processEvent' is not used

### ISSUE THREAD

**Issue by krisvandebroek** [ing-bank/baker#112]
When you call `baker.processEvent(processId, event, Duration.ofSeconds(20));` this timeout should be used. However in the Baker class, in method `public SensoryEventStatus processEvent(String processId, Object event, FiniteDuration timeout)`, this timeout is ignored and the default timeout of 10 seconds is used.

[Edit]
We are currently using version 1.3.1.1-RC from Java.

**Comment by merlijn** [comment]
Will investigate, which version are you using?

**Comment by krisvandebroek** [comment]
@merlijn: We are using 1.3.1.1-RC from Java. When I look at the source code for 1.3.1 (1.3.1.1-RC does not exist as tag) the method actually doesn't seem to use the 'timeout' parameter.
Although the decompiled code by Intelllij for 1.3.1.1-RC gives
`
    public SensoryEventStatus processEvent(String processId, Object event, FiniteDuration timeout) throws NoSuchProcessException, ProcessDeletedException, TimeoutException {
        return this.processEventAsync(processId, event, this.processEventAsync$default$3()).confirmCompleted();
    }
`

**Comment by krisvandebroek** [comment]
@merlijn : Looking at Git, it seems you fixed it in commit 00dbded. That version 1.3.4 is not yet released. Can you create a release of this version?

**Comment by merlijn** [comment]
@krisvandebroek Yes you are right, in that version a default is used by mistake. We are working on releasing 1.4.0 soon.

**Comment by merlijn** [comment]
Closing this, fix will be released in 1.4.0.

**Comment by krisvandebroek** [comment]
@merlijn: I tested the latest version. It partially solves the issue. I've created mergerequest #113 to finish it up. Can you look into this?
