### ISSUE TITLE
Improve performance of initial bake (create) call

### ISSUE THREAD

**Issue by merlijn** [ing-bank/baker#114]
In the case of a `bake(..)` we perform 2 write and 1 read operation on the persistence journal.

The read operation can be omitted by passing `Recovery.none` on the first create. 

This is blocked by https://github.com/akka/akka/issues/25072

**Comment by merlijn** [comment]
In the recipe petri net there are a lot of transitions that basically *do nothing*. 

An optimisation could be to *not* persist these.

The effect of these transitions can simply be re-computed and applied on replay.

This would significantly reduce the number of persisted messages.

**Comment by Tim-Linschoten** [comment]
Since "Preliminary tests" do not show big enough improvements we will close this.
