### ISSUE TITLE
More boilerplate needed when creating a Scala baker instance than for Java

### ISSUE THREAD

**Issue by jlengrand** [ing-bank/baker#12]
To stick with the documentation when creating my first recipe I have been using the _JBaker_ object.
However today I refactored the code to be full Scala.

Using JBaker 

```Scala
val baker = new JBaker(
      recipe,
      ImmutableList.<Interaction>of(
                ...
        );
    )
```

while using Baker directly requires more boilerplate

```Scala
  implicit val timeout: FiniteDuration = new FiniteDuration(10, java.util.concurrent.TimeUnit.SECONDS)
    val baker = new Baker(
      recipe,
      implementations = Map(
        classOf[InteractionExample] -> (() => new InteractionExample()),
        ....
      ),
      actorSystem = ActorSystem.apply("BakerActorSystem", JBaker.defaultConfig)
    )
```

It would be nice to have a SBaker object, just like for Java, that avoids having to consider things like actorSystems and timeout. 

Especially since those items are currently not part of the available documentation 👼

**Comment by bekiroguz** [comment]
This is already improved with the recent additions to the scaladsl.
