### ISSUE TITLE
EventResult cannot be resolved

### ISSUE THREAD

**Issue by oene** [ing-bank/baker#1243]
Following the tutorial: https://ing-bank.github.io/baker/sections/development-life-cycle/bake-fire-events-and-inquiry/

I get:

> EventResult cannot be resolved

> The import com.ing.baker.runtime.javadsl.EventResult cannot be resolved

on import:

`import com.ing.baker.runtime.javadsl.EventResult;
`

and code:

`        CompletableFuture<List<String>> result = baker.addInteractionInstance(reserveItemsInstance)`
`           .thenCompose(ignore -> baker.addRecipe(compiledRecipe))`
`           .thenCompose(recipeId -> baker.bake(recipeId, recipeInstanceId))`
`           .thenCompose(ignore -> baker.fireEventAndResolveWhenCompleted(recipeInstanceId, firstOrderPlaced))`
`           .thenApply(EventResult::events);`

**Comment by Tim-Linschoten** [comment]
Hello, 

It seems we forgot to update our documentation on here after we renamed the EventResult to SensoryEventResult.

Try the following:

`import com.ing.baker.runtime.javadsl.SensoryEventResult`


`CompletableFuture<List<String>> result = baker.addInteractionInstance(reserveItemsInstance)`
`.thenCompose(ignore -> baker.addRecipe(compiledRecipe))`
`.thenCompose(recipeId -> baker.bake(recipeId, recipeInstanceId))`
`.thenCompose(ignore -> baker.fireEventAndResolveWhenCompleted(recipeInstanceId, firstOrderPlaced))`
`.thenApply(SensoryEventResult::eventNames);`
