### ISSUE TITLE
Test in ExampleSpec is ignored and broken

### ISSUE THREAD

**Issue by kevinvandervlist** [ing-bank/baker#137]
The `ExampleSpec` has a `run a happy flow` which is ignored (as far as I know since December last year). It still is the entry point to Baker based on your project's README and show a coding style also presented in the video recorded at 'scale by the bay'. 

The error is:

```
Unsupported parameter type for interaction implementation 'Tuple2'
java.lang.IllegalArgumentException: Unsupported parameter type for interaction implementation 'Tuple2'
	at com.ing.baker.runtime.core.interations.MethodInteractionImplementation.$anonfun$inputTypes$1(MethodInteractionImplementation.scala:145)
[...]
```

and happens when implementations (via the implicit `implement`) of interactions are added to Baker. The tuple comes from the return type of the `implement` and has the following signature: `(String, Seq[Any] => Any)`

So my questions are basically:
* Is this example still representative on how to use the project and is this just a bug?
* Or, is there another example on how to use this (preferably executable)?

**Comment by merlijn** [comment]
Thanks for reporting!

You are right, due to some refactoring this was set to ignore but never fixed.

I have a PR now to fix this: https://github.com/ing-bank/baker/pull/138

**Comment by kevinvandervlist** [comment]
Thanks, PR works for me 👍
