### ISSUE TITLE
RFI: Baker versus Apache Camel

### ISSUE THREAD

**Issue by HighTML** [ing-bank/baker#168]
Could somebody make a comparison of Baker and Apache Camel? I’m wondering what added benefits Baker offers. Camel also has a DSL, supports REST services and implements a lot of integration patterns.

**Comment by bekiroguz** [comment]
Hi,
I do not see that many commonalities between Baker and Apache Camel. They're tools to solve different problems I think.

1. Baker is designed to describe and execute process flows in a distributed/persistent/clustered environment, but Camel is a library to make "integration" between various types of systems easier.

2. Baker is an event-based process flow orchestration library, so you fire some events to Baker which may have also ingredients (data) in them, and all interactions with dependencies to those events or ingredients are executed automatically in order or in parallel. Camel just consumes data from endpoints, transforms data and sends to other endpoints.

3. A Baker recipe is compiled/validated against loops, unused events, or interactions which may never fire. So, when a Recipe compiles, you know it is complete and sound. A visual recipe is also auto-generated from code so you can print and discuss your process flow with other non-tech stakeholders as well. 

I know Camel is a huge library with many ready-to-use components, supports various endpoints, but the core of the library is for integration. 

On the other hand, the core of Baker is a mathematical model of a process flow (PetriNet), persistence with event sourcing pattern, horizontal scalability with the help of clustering features of Akka library. 

I hope this short comparison helps,
Bekir

**Comment by HighTML** [comment]
Hi, 
Thanks for your explanation. So Baker is a sort of workflow engine for short-lived STP processes.
