### ISSUE TITLE
Name changes

### ISSUE THREAD

**Issue by merlijn** [ing-bank/baker#179]
Some class and function names do not make sense.

For a baker `3.0.0` release there is an opportunity to change them.

Examples:

`Baker.bake(..)` - `createInstance` or `createProcess` would be more explanatory.
`Baker.processEvent(..)` - *process* here is confusing since we also talk about *process* instances.
`CompiledRecipe` - *Compiled* is not necessary, you also do not call a program a *compiled* program
`RuntimeEvent`- *Runtime* is a confusing term, perhaps `RecipeEvent` or `ProcessEvent` is better.

**Comment by Tim-Linschoten** [comment]
We are going to re-evaluate the interface of Baker, we will take these into consideration when we do that.
