### ISSUE TITLE
Using baker in a distributed environment

### ISSUE THREAD

**Issue by pedramha** [ing-bank/baker#189]
Is it possible to define the interactions on remote machines?
As I get it, Baker does not support REST calls over HTTP in the recipe itself, right?

**Comment by bekiroguz** [comment]
Currently all interactions are fired from the same actor, so the same machine. The recipe execution, and so called the PetriNet model of the recipe is encapsulated inside the actor. The HTTP calls to the remote services can be done inside the interactions, and some interactions may still be fired in parallel depending on your recipe.

I hope this answers your question. You can see the concepts also explained here: https://ing-bank.github.io/baker/documentation/concepts/
