### ISSUE TITLE
Access to completable future in baker.processEventAsync()

### ISSUE THREAD

**Issue by dfollen-ing** [ing-bank/baker#198]
Hi

We are migrating from 1.4 to 2.0.3 and we see that the `BakerResponse.completedFuture()` has been removed (or made private).  
We used to have the following:
```java
return FutureConverters.toJava(bakerResponse.completedFuture())
                .toCompletableFuture()
                .handle((r, t) -> {
                    if (t != null) {
                        if (t instanceof TimeoutException) {
                            throw new SomeInternalException(t,"");
                        }
                        throw new SomeInternalException(t,"");
                    }
                    return r;
                });
```
 Unfortunately, we need an equivalent mechanism to truly stay async: using `bakerResponse.confirmCompleted()` block and removes the async advantage. Would it be possible to somehow expose a callback on the `com.ing.baker.runtime.core.BakerResponse` (a java `CompletableFuture` would be perfect)?

**Comment by FrancoAra** [comment]
I'll take this one :)

**Comment by FrancoAra** [comment]
https://github.com/ing-bank/baker/pull/199
