### ISSUE TITLE
Clean up of dependencies

### ISSUE THREAD

**Issue by dfollen-ing** [ing-bank/baker#205]
Hi

When building baker (2.0.5) dependant projects with the maven enforcer plugin, the build fails complaining about different versions of the dependencies from the libraries:
`com.github.dnvriend:akka-persistence-inmemory_${scala-compiler.version}` depends on a different version of the following akka dependencies than baker:
- akka-persistence-query_${scala-compiler.version}
- akka-persistence_${scala-compiler.version}
- akka-actor_${scala-compiler.version}
- akka-stream_${scala-compiler.version}  
The issue is the same for: `org.typelevel:cats-effect_${scala-compiler.version}`
- cats-core_${scala-compiler.version}

It could be a good idea to clean up the dependencies to make sure that you get the right version packaged in your application.
We have that in our pom file to solve the issue:
```xml
 <dependency>
                <groupId>com.github.dnvriend</groupId>
                <artifactId>akka-persistence-inmemory_${scala-compiler.version}</artifactId>
                <version>2.5.1.1</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.typesafe.akka</groupId>
                        <artifactId>akka-persistence-query_${scala-compiler.version}</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.typesafe.akka</groupId>
                        <artifactId>akka-persistence_${scala-compiler.version}</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.typesafe.akka</groupId>
                        <artifactId>akka-actor_${scala-compiler.version}</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.typesafe.akka</groupId>
                        <artifactId>akka-stream_${scala-compiler.version}</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.typelevel</groupId>
                <artifactId>cats-effect_${scala-compiler.version}</artifactId>
                <version>0.10</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.typelevel</groupId>
                        <artifactId>cats-core_${scala-compiler.version}</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```

**Comment by Tim-Linschoten** [comment]
Hello David,

What we notice is that if we do exclude in our libraries the enforcer plugin completely ignores this.
The only way to keep it happy is do these exclusions and dependencies fixes in your own pom.

Regards,

Tim Linschoten
