### ISSUE TITLE
jbaker.getEventAsync() exposure

### ISSUE THREAD

**Issue by dfollen-ing** [ing-bank/baker#206]
Hi

Would it be possible to expose the baker `eventsAsync(processId: String)` of Baker in the JBaker class? 
That would be pretty useful.
Edit:
Would it also be possible to expose the `bakeAsync` method?

Thanks

David

**Comment by Tim-Linschoten** [comment]
Hello David, we are going to change our approach to async operations.
All our normal operations (bake, processEvent, getProcessState etc..) will be async by default.
We will work on this in the coming weeks.
I hope this is soon enough for you.

**Comment by dfollen-ing** [comment]
Hi Tim,
Sounds good to me, thanks!

**Comment by Tim-Linschoten** [comment]
A small update,
We just released Baker 3.0.0-RC.
This includes the changes we discussed.

Migration guide is in the works and should be done soon.
