### ISSUE TITLE
`Event` and `Ingredient` override `equals` but don't override `hashcode`

### ISSUE THREAD

**Issue by anshee** [ing-bank/baker#216]
Several classes, most importantly [Event](https://github.com/ing-bank/baker/blob/master/recipe-dsl/src/main/scala/com/ing/baker/recipe/common/Event.scala) and [Ingredient](https://github.com/ing-bank/baker/blob/master/recipe-dsl/src/main/scala/com/ing/baker/recipe/common/Ingredient.scala) override `equals` but do not override `hashcode` - and so they violate `hashcode` contract.

This will cause problems when - for example - these objects are stored in collections using hashing, like HashSet. One way to reproduce (it's just to show the failure, so recipes don't make much sense) is when Scala switches from specialized Set.SetN implementation to HashSet when set grows beyond 4 elements:

```java
    static class EventA {}
    static class EventB {}
    static class EventC {}
    static class EventD {}
    static class EventE {}

    @Test
    public void test() {

        // "Duplicated" EventA will not be added
        // Because Set backing sensoryEvents has <=4 elements (is a specialized Set.Set4) and only uses `equals` in `contains`
        Recipe recipe1 = new Recipe("recipe1")
                .withSensoryEvents(EventA.class, EventB.class, EventC.class, EventD.class)
                .withSensoryEventsNoFiringLimit(EventA.class);
        log.info("Recipe1 set [{}]", recipe1.sensoryEvents().getClass());
        log.info("Recipe1 has [{}] sensory events [{}]", recipe1.sensoryEvents().size(), recipe1.sensoryEvents());

        // "Duplicated" EventA will be added
        // Because Set backing sensoryEvents has >4 elements (is a HashSet) and uses `hashcode` in `contains`
        Recipe recipe2 = new Recipe("recipe2")
                .withSensoryEvents(EventA.class, EventB.class, EventC.class, EventD.class, EventE.class)
                .withSensoryEventsNoFiringLimit(EventA.class);
        log.info("Recipe2 set [{}]", recipe2.sensoryEvents().getClass());
        log.info("Recipe2 has [{}] sensory events [{}]", recipe2.sensoryEvents().size(), recipe2.sensoryEvents());

        // So compilation of Recipe1 succeeds because there are no "duplicates"
        RecipeCompiler.compileRecipe(recipe1);

        // But compilation of Recipe2 will fail
        RecipeCompiler.compileRecipe(recipe2);
    }
```

Additionally, notion of equality for Event seems inconsistent:
- has 3 fields: `name`, `providedIngredients` and `maxFiringLimit`
- `equals` takes into account only `name` and `providedIngredients`
- `Assertions.assertNoDuplicateElementsExist` only checks the name

**Comment by Tim-Linschoten** [comment]
Hey Maciej ,

We will look into this for our next release.
Thank you for letting us know!
