### ISSUE TITLE
Implement a Baker interface using cats effect

### ISSUE THREAD

**Issue by FrancoAra** [ing-bank/baker#271]
Implement a Baker interface that uses cats effect type classes to properly wrap the Futures into different possible effect types.

Baker is properly abstracted with an interface located at `com.ing.baker.runtime.common.Baker`, this allows us to make different implementations that respect the baker DSL. With the cats effect library, you can also abstract the effect type (like Future or IO) using the cat's effect type classes, some libraries that do this are: fs2, http4s and doobie. This would allow the users of Baker to use any prefered effect type besides Future, like ZIO, cats effect IO, or Monix Task.

**Comment by ayushworks** [comment]
This would have been doable without looking at internals. However  `com.ing.baker.runtime.akka.internal.InteractionManager` directly uses an implementation `InteractionInstance[Future]` instead of using the interface `InteractionInstance[F[_]]`. 

So , creating a new Baker interface like 

```
class AkkaEffectBaker[F[_]: Async: Monad] private[runtime](config: AkkaBakerConfig) extends Baker[F]
```
is not possible without also changing some classes in `internal` package..

Is that a right assessment?

**Comment by FrancoAra** [comment]
All futures can be transformed to any effect type that implements async :) there is a small example at the cats effect docs https://typelevel.org/cats-effect/typeclasses/async.html

**Comment by FrancoAra** [comment]
So since every Future can become any Async, it should be matter of mapping the AkkaBaker implementation for now, later on maybe we could make a Baker runtime without Akka! :D

**Comment by ayushworks** [comment]
hmmm...i was thinking of writing an effectfull version `AkkaBaker` and wrapping the `akka` operations in cats-effect

```
override def addRecipe(compiledRecipe: CompiledRecipe): F[String] = {

    // check if every interaction has an implementation
    val implementationErrors = getImplementationErrors(compiledRecipe)

    if (implementationErrors.nonEmpty)
      Async[F].raiseError(new ImplementationsException(implementationErrors.mkString(", ")))

    else if (compiledRecipe.validationErrors.nonEmpty)
      Async[F].raiseError(new RecipeValidationException(compiledRecipe.validationErrors.mkString(", ")))

    else Async[F].async[String] {
      cb =>
        val fut = recipeManager.ask(RecipeManagerProtocol.AddRecipe(compiledRecipe))(config.defaultAddRecipeTimeout) map {
          case RecipeManagerProtocol.AddRecipeResponse(recipeId) => recipeId
        }
        fut.onComplete {
          case Success(value) => cb(Right(value))
          case Failure(exception) => cb(Left(exception))
        }
    }
  }
```

**Comment by FrancoAra** [comment]
That is for sure one option, but maintaining it would be a slight pain, because there wont be a single source of truth, if the semantics of an operation changes, then we need to make the same change on both APIs

**Comment by FrancoAra** [comment]
There is the easiest one which is to depend on an AkkaBaker implementation and do something like:

```scala
override def addRecipe(compiledRecipe: CompiledRecipe): F[String] = {
  Async[F].async[String] { cb =>
    akkaBaker.addRecipe.onComplete {
      case Success(v) => cb(Right(v))
      case Failure(e) => cb(Left(e))
    }
  }
}
```

**Comment by FrancoAra** [comment]
In that way if we change the akka implementation it changes for both APIs

**Comment by ayushworks** [comment]
OK. Then I will pick this up 👍

**Comment by nightscape** [comment]
@FrancoAra is this closed because it is implemented now?
I just stumbled upon https://github.com/evolution-gaming/akka-effect which provides typeclasses  using an `F[_]` type argument for Akka and Akka Persistence.
Would this be sufficient?
Would you be interested in a PR?
