### ISSUE TITLE
Provide an example of the DSL in your README

### ISSUE THREAD

**Issue by agemooij** [ing-bank/baker#33]
Hi

I followed a link to this project from a newsletter and was surprised to realize that the README mentions recipes only as images but never actually shows the DSL to reproduce those recipes. I tried to find an example in the test code but couldn't figure it out within 5 minutes.

I think it would really help people evaluating your library if you have a coupe of code examples in the README.

**Comment by merlijn** [comment]
Thanks for your feedback! Indeed the documentation / examples are a bit lacking. We are picking this up ASAP.

**Comment by bekiroguz** [comment]
Fixed by 4aef0aebe2db557f62c724728b40265602575596. Added webshop recipe to the readme file together with a link to the ExampleSpec.
