### ISSUE TITLE
BakerResponse should support waiting until an event to happen

### ISSUE THREAD

**Issue by bekiroguz** [ing-bank/baker#41]
At the moment when an event is handled by baker, a BakerResponse object is returned, and it has 2 methods: confirmReceived and confirmCompleted. 
In many cases, what we do is calling confirmCompleted, and in the next line looking for an event (eventually consistent) or an ingredient (consistent) to be available, and return a different http response accordingly.

And also the eventual consistency behaviour of the baker.events() is not easily guessed from the name, and not well known by many developers. This sometimes causes bugs due to misassumptions.

It would be nicer to add the possibility to wait until some event or some ingredient available when we call confirmReceived or confirmCompleted methods. Or maybe make a new method for that.

And the confirmation of the ingredient or event should be done synchronously (eventual consistency is not a good pattern here).

**Comment by Tim-Linschoten** [comment]
Due to complete refactor of the response object this now possible.
In Baker V3 this will be available for users.

`baker.fireEventAndResolveOnEvent(processId, EventInstance.from(ExampleEvent), "EventToWaitOn");`
