### ISSUE TITLE
Unclear that events from multiple interactions work with AND condition.

### ISSUE THREAD

**Issue by Tim-Linschoten** [ing-bank/baker#42]
If and event can be fired from multiple interactions it is only fired into the decision model (petri-net) if all interactions have provided this event.
In the event list the event is still found even if the event will not be fired for the petri-net.

This is unclear for the users of Baker. They expect this to be a OR condition.
We should make this as the user expect by doing one the following:
1. Make it a OR condition
2. Disallow having multiple interactions fire the same event in the compiler.

**Comment by merlijn** [comment]
This behaviour is very counter intuitive. I would consider this a bug.

We can start by disallowing this altogether and maybe later add this as a feature.
