### ISSUE TITLE
Baker metrics

### ISSUE THREAD

**Issue by merlijn** [ing-bank/baker#61]
We should report metrics that users of Baker could be interested in.

To decide:

- Which framework, codahale metrics?
- Which metrics, for example: interaction execution time.

**Comment by sebastianharko** [comment]
@merlijn @bekiroguz Anyone working on this one ? I'd like to take this one. Cheers!

**Comment by merlijn** [comment]
Hi Sebastian,

Great that you are willing to work on this one. Nobody is working on this yet so go ahead!

Perhaps we can start with the 'interaction execution time' metric. 

Do you have any thoughts about others?. I will think on it an post a list of metrics that might be useful.

**Comment by sebastianharko** [comment]
Interaction execution time would be a good one to start.. Cheers!

**Comment by merlijn** [comment]
Closing this. Metrics can be build as an extension on top of the new event listening api
