### ISSUE TITLE
Failure Strategy with initial delay and maxTimesbetweenRetries, initial delay is not being used

### ISSUE THREAD

**Issue by edwarddegraaf** [ing-bank/baker#66]
Example :
.withFailureStrategy(RetryWithIncrementalBackoff(Duration.ofHours(4), Duration.ofDays(1), Duration.ofHours(2))),
 
If you add an failure strategy with intial delay and maxTimesBetweenRetries the initial delay is not used.
 
Is this correct behaviour?

**Comment by merlijn** [comment]
Last time I looked I could not reproduce.

Is this still an issue?

**Comment by edwarddegraaf** [comment]
Hoi merlijn

Ik heb de werking verkeerd begrepen. Ik dacjt dat het anders zou werken. My
mistake da make

Groeten

Edward

Op 25 jan. 2018 4:43 p.m. schreef "Merlijn van Ittersum" <
notifications@github.com>:
