### ISSUE TITLE
Join akka cluster after persistence warmup actor succeeds to start

### ISSUE THREAD

**Issue by bekiroguz** [ing-bank/baker#69]
In case there's no connection to any local cassandra nodes, this warmup actor times out but baker already started the actor system and joined the akka cluster which means, started already receiving actor messages, sharding region handover messages, etc... And these will all fail because there's no connection to local cassandra nodes in local data center.

Joining to cluster should be done after successfully connecting to cassandra, which could be done by hooking into the warmup actor status...

**Comment by sebastianharko** [comment]
@bekiroguz Have you guys activated the eager initialization of the persistence plugin (available in akka) ? Shouldn't that get rid of the warmup actor ?

**Comment by bekiroguz** [comment]
Thanks @sebastianharko, I think we can apply eager initialization. I remember there were some other reasons so we implemented this warmup actor, but not needed anymore. I will test.

**Comment by bekiroguz** [comment]
@sebastianharko: What's important for us is joining cluster after successfully connecting to cassandra. The nodes which cannot connect to cassandra should not be part of the akka cluster.
