### ISSUE TITLE
should assert on compile @FiresEvent.oneOf type matches apply method return type

### ISSUE THREAD

**Issue by pascal-warnimont** [ing-bank/baker#85]
`        @FiresEvent(oneOf = {ExampleEvent.class})
        public SomeEvent apply(
`

yields msg text on runtime:

"... but could not link it to any known event for the interaction..."

while info is available at recipe compile time

**Comment by merlijn** [comment]
Hi, is this still an issue?

For me there is not enough information investigate.

What could not be linked to what exactly? 

Please provide more context if this is still an issue.

If this is not an issue anymore, can you comment, then I can close it.

**Comment by pascal-warnimont** [comment]
am on another project since 2 month, sorry for that, but out of memory, the point is that this error can be detected at code generation / compile time since the type in the annotation does not match the explicitly declared type of the apply method. So this is not critical, but more to improve the DSL

**Comment by davfo224** [comment]
In the example of Pascal, the baker framework could, at recipe compile time, assert that `ExampleEvent ` extends `SomeEvent` or create an error in case the result and the expected fired event are not compatible in terms of class hierachy
