### ISSUE TITLE
the .withSensoryEvents should only accept events and not any object

### ISSUE THREAD

**Issue by Tim-Linschoten** [ing-bank/baker#9]

**Comment by Tim-Linschoten** [comment]
We want to have more type safety in our DSL so we should only accept the correct types as input for our DSL.

**Comment by jlengrand** [comment]
HEy @Tim-Linschoten, 

I was trying to fix this as well to get to know the codebase better.

Can you tell me why is the JRecipe _events_ value also not being restricted to only accept Events? OR do you consider enough to restrict the inputs from external methods.

https://github.com/ing-bank/baker/blob/withSensoryEventsOnlyAcceptsEvents/core/src/main/scala/com/ing/baker/java_api/JRecipe.scala#L19

Thanks :)

**Comment by jlengrand** [comment]
For reference, [here is my WIP for this issue](https://github.com/jlengrand/baker/pull/1/files)
