### ISSUE TITLE
Support OpenTracing in Baker

### ISSUE THREAD

**Issue by srouault** [ing-bank/baker#98]
Include opentracing in Baker, to trace incoming requests and Client Interactions.

**Comment by nikolakasev** [comment]
Input for the design session on this:

a. A span maps to an execution of an interaction?
b. When an interaction is retried, a new span is created?
c. How does the processId fit in the specification? Use the parentId as processId?

**Comment by merlijn** [comment]
This can be build using #119 as an extension to baker

**Comment by merlijn** [comment]
Closing, this can be build as an extension using the event listening API. 

Or, if that is not enough, we need to create a way to pass a context.

That is another issue.
